# Generated by Django 3.2.5 on 2021-07-15 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_site', '0002_rename_user_post_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='subscriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
